# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:macos)


app_store_connect_api_key(
  key_id: "8MXL67G25U",
  issuer_id: "69a6de84-c7ac-47e3-e053-5b8c7c11a4d1",
  key_filepath: "~/Downloads/AuthKey_8MXL67G25U.p8"
)
