# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:macos)

# https://appstoreconnect.apple.com/access/api
# if running locally, use this format
# app_store_connect_api_key(
#   key_id: "[key]",
#   issuer_id: "[id]",
#   key_filepath: "/path/to/key.p8"
# )

app_store_connect_api_key
# in CI, we use the env vars
# LANG=UTF-8 LC_ALL=UTF-8
# APP_STORE_CONNECT_API_KEY_KEY_ID=“xxxxxx”
# APP_STORE_CONNECT_API_KEY_ISSUER_ID=“xxxxxx”
# APP_STORE_CONNECT_API_KEY_KEY="-----BEGIN EC PRIVATE KEY-----\nxxxxxxxxx\n-----END EC PRIVATE KEY-----” 
# APP_STORE_CONNECT_API_KEY_IN_HOUSE=false # optional but might be needed in match
